name: PvPLevels
author: corytortoise
main: corytortoise\PvPLevels\Main
version: "1.0"
api: 3.0.0
description: Stores PvP stats and enables leveling for kills.

commands:
  pvpstats:
    description: Shows PvP Statistics
    usage: /pvpstats [player]
